version: '0.1'
services:
  proxy:
    #build: .
    image: nginx:alpine
    #ports:
    #- "8444:8444"
    volumes:
    - ./template/nginx.conf:/etc/nginx/nginx.conf
    cap_add:
    - NET_ADMIN
    net: "host"

