version: '3'
services:
  proxy:
    #build: .
    image: nginx:alpine
    #ports:
    #- "8444:8444"
    volumes:
    - ./template/nginx.conf:/etc/nginx/nginx.conf
    cap_add:
    - NET_ADMIN
    network_mode: "host"
    restart: always

